## Numpy Array Operations 


In [3]:
import numpy as np

In [8]:
arr = np.arange(10)
print("Arr :- ", arr)
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])


Arr :-  [0 1 2 3 4 5 6 7 8 9]
Basic Slicing [2 3 4 5 6]
With Step [1 3 5 7]
Negative indexing 7


In [9]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire column: ", arr_2d[:, 1])

Specific element 6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


### Sorting :- 


In [14]:
unsorted = np.array([9,6,2,1,3,4,8])
print("Sorted Array :- ",np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("unsorted array :-")
print(arr_2d_unsorted)

print("Sorted 2D array by column")
print(np.sort(arr_2d_unsorted, axis=0)) # axis = 0 (Coulumn-wise sorting), axis = 1 (row-wise sorting)


Sorted Array :-  [1 2 3 4 6 8 9]
unsorted array :-
[[3 1]
 [1 2]
 [2 3]]
Sorted 2D array by column
[[1 1]
 [2 2]
 [3 3]]


### Filter :-


In [15]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


### Filter with mask :- 

In [16]:
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


### Fancy indexing vs np.where() :-

In [17]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [19]:
condition_array = np.where(numbers > 5, "true",  "false") # true will execute if condition is true otherwise false
print(condition_array)

Example = np.where(numbers%2==0,numbers*5 , numbers)
print(Example)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']
[ 1 10  3 20  5 30  7 40  9 50]


### Adding and Removing data :- 

In [20]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### Array Compatability :-

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes False


In [24]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print(original)
print("\n",with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With new column")
print( with_new_col)

[[1 2]
 [3 4]]

 [[1 2]
 [3 4]
 [5 6]]
With new column
[[1 2 7]
 [3 4 8]]


In [26]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5]
