## Numpy Array And Basics

learning about Numpy :-

In [1]:
import numpy as np

### Creating array from list :-

In [21]:
arr_1d = np.array([1,2,3,4,5])
print("1D arrays",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D arrays :- ")
print(arr_2d)


1D arrays [1 2 3 4 5]
2D arrays :- 
[[1 2 3]
 [4 5 6]]


### List vs Numpy Array :-


In [3]:
py_list = [1,2,3]
print("Python list Multiplication ", py_list*2)

np_array = np.array([1,2,3])
print("Python array Multiplication ", np_array*2)

Python list Multiplication  [1, 2, 3, 1, 2, 3]
Python array Multiplication  [2 4 6]


### Creating Array from scratch :-

In [13]:
zeors = np.zeros((3,4))
print("zeros array: \n",zeors,end='\n\n')

ones = np.ones((2,3))
print("Ones array: \n",ones,end='\n\n')

full = np.full((2,2),7)
print("full array: \n",full,end='\n\n')

random = np.random.random((2,3))
print("random array: \n",random,end='\n\n')

sequnece = np.arange(0,10,2)
print("Sequence array: \n",sequnece,end='\n\n')


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]

full array: 
 [[7 7]
 [7 7]]

random array: 
 [[0.00559675 0.71673341 0.04643197]
 [0.32767617 0.1865721  0.49211743]]

Sequence array: 
 [0 2 4 6 8]



### Vector , Matrix and Tensor :-


In [23]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[2,3,4],
                   [3,4,5]])
print("Matrix: ")
print(matrix)

tensor = np.array([[[2,3,5],[9,7,4]],
                   [[3,1,4],[4,1,4]]])
print("Tensor: ")
print(tensor)

Vector:  [1 2 3]
Matrix: 
[[2 3 4]
 [3 4 5]]
Tensor: 
[[[2 3 5]
  [9 7 4]]

 [[3 1 4]
  [4 1 4]]]


### Array Properties :-



In [18]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape ",arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


### Array Reshaping :-

In [27]:
arr = np.arange(12)
print('Original Array',arr)

reshaped = arr.reshape((3,4))
print("\nReshaped Array:- ")
print(reshaped)

flattened = reshaped.flatten()
print("\nFlatened Array :- ",flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ")
print(transpose)

Original Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array:- 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flatened Array :-  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array 
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
